### ISSUE TITLE
error: config: no rules were found! Do you need to run 'sa-update'?

### ISSUE THREAD

**Issue by arkag** [tiredofit/docker-spamassassin#3]
### Summary

Configuration isn't being detected, do I need to apply a default configuration or is what's in `config` all that I need?

```
spamassassin-app    | 2021-08-24-17:21:08 [STARTING] ** [spamassassin] [35] Starting spamassassin
spamassassin-app    | 2021-08-24-17:21:08 [STARTING] ** [monitoring] [35] Starting Zabbix Agent (modern) 5.4.3
spamassassin-app    | Aug 24 17:21:09.284 [4204] error: config: no rules were found! Do you need to run 'sa-update'?
spamassassin-app    | config: no rules were found!  Do you need to run 'sa-update'?
```

### Steps to reproduce

`docker-compose.yml`:
```
version: '3.7'
services:
  spamassassin-app:
    image: tiredofit/spamassassin:latest
    container_name: spamassassin-app
    ports: 
    - 783:783
    volumes:
    - ./logs/spamassassin:/var/log/spamassassin
    - ./conf:/etc/mail/spamassassin
    - ./data:/var/lib/spamassassin
    networks:
    - internal
    - services
    restart: always
  clamav-app:
    image: tiredofit/clamav:latest
    container_name: clamav-app
    ports: 
    - 3310:3310
    volumes:
    - ./data:/var/lib/clamav
    - ./logs:/var/log/clamav
    environment:
    - DEFINITIONS_UPDATE_FREQUENCY=60
    networks: 
    - internal
    - services
    restart: always
networks:
  internal:
    external: false
  services:
    external: true
```

### What is the expected *correct* behavior?

The app starts up without issue.

### Environment

- Image version / tag:  latest
- Host OS: Ubuntu 20.04
    
### Possible fixes
Seems like I don't have the correct pathing for the configuration set up, but this was pulled from the example in the example directory.
